### ISSUE TITLE
Remove ImagemModel.belongsTo(models.LesaoModel)

### ISSUE THREAD

**Issue by rgaiacs** [CRICDatabase/searchable-image-database-nodejs#15]
From my understanding,

1. image has one or more cells
2. cell has one **and only one** lesion
3. lesion are defined in the literature

If 1-3 is true, `ImagemModel.belongsTo(models.LesaoModel)` doesn't make any sense.

**Comment by bernardofagner** [comment]
Boa tarde Raniere. Os relacionamentos foram definidos com base no que o minimundo apresenta. Dê uma lida lá e se ainda não fozer sentido para você a gente marca uma chamada de Hangouts junto com a Andrea e explicamos a você, blz?

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________
